image: python:3.11-bullseye

variables:
  GIT_LFS_SKIP_SMUDGE: "1"

workflow:
  rules:
  - if: $CI_COMMIT_BRANCH == "master"
    when: always
  - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'master'
    when: always
  - when: never

before_script:
  - pip install -r requirements-core.txt
  - export PYTHONPATH="$PYTHONPATH:$(pwd)"

linters:
  script:
    - pip install pylint ruff
    - python -m pylint --rcfile=.pylintrc $(git ls-files "*.py" | grep -v "test")
    - ruff check

unit_tests:
  script:
    - apt-get update
    - pip install pytest
    - pytest test/robochan/unit test/roboimpl/unit

e2e_tests:
  script:
    - apt-get update
    - apt install -y lsof netcat ffmpeg git

    - git clone --depth 1 --filter=blob:none --sparse https://gitlab.com/video-representations-extractor/video-representations-extractor.git /tmp/vre
    - cd /tmp/vre && git sparse-checkout set resources && cd -
    - cp /tmp/vre/resources/test_video.mp4 test/e2e/video-udp-screenshot/test_video.mp4
    - bash test/e2e/run_all.sh
